# -*- coding: utf-8 -*-
"""ex5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWXfai41-IZ3XrPvCc_c-r2SF8rEt33D
"""

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

# ==============================
# UPLOAD CSV FILE
# ==============================

uploaded = files.upload()

# Get the uploaded file name automatically
file_name = next(iter(uploaded))

# Read CSV file
df = pd.read_csv(
    file_name,
    engine="python",
    on_bad_lines="skip"
)

# Display column names
print("Columns in dataset:")
print(df.columns)

# Convert relevant columns to numeric, coercing errors and dropping NaNs
df['Calories'] = pd.to_numeric(df['Calories'], errors='coerce')
df.dropna(subset=['Calories'], inplace=True)

df['Protein\n(g)'] = pd.to_numeric(df['Protein\n(g)'], errors='coerce')
df.dropna(subset=['Protein\n(g)'], inplace=True)


# ==============================
# 1. TOP 10 FOOD COMPANIES - BAR CHART
# ==============================

top = df["Company"].value_counts().head(10)

plt.figure(figsize=(10, 5))

plt.bar(top.index, top.values)

plt.xticks(rotation=45, ha="right")
plt.xlabel("Company")
plt.ylabel("Count")
plt.title("Top 10 Food Companies")

plt.tight_layout()
plt.show()


# ==============================
# 2. TOP 10 FOOD COMPANIES - PIE CHART
# ==============================

category = df["Company"].value_counts().head(10)

plt.figure(figsize=(8, 8))

plt.pie(
    category.values,
    labels=category.index,
    autopct="%1.1f%%",
    startangle=90,
    pctdistance=0.8,
    textprops={"fontsize": 10}
)

plt.title("Top 10 Food Companies")

plt.tight_layout()
plt.show()


# ==============================
# 3. CALORIE DISTRIBUTION - HISTOGRAM
# ==============================

plt.figure(figsize=(8, 5))

plt.hist(
    df["Calories"],
    bins=15,
    edgecolor="black"
)

plt.xlabel("Calories (kcal)")
plt.ylabel("Frequency")
plt.title("Distribution of Calories")

plt.tight_layout()
plt.show()


# ==============================
# 4. CALORIES VS PROTEIN - SCATTER PLOT
# ==============================

plt.figure(figsize=(8, 6))

plt.scatter(
    df["Calories"],
    df["Protein\n(g)"],
    alpha=0.7
)

plt.xlabel("Calories (kcal)")
plt.ylabel("Protein (g)")
plt.title("Calories vs Protein")

plt.tight_layout()
plt.show()


# ==============================
# 5. CALORIES - BOX PLOT
# ==============================

plt.figure(figsize=(5, 7))

plt.boxplot(df["Calories"])

plt.title("Calories Box Plot")
plt.ylabel("Calories (kcal)")

plt.tight_layout()
plt.show()


# ==============================
# 6. TOP 20 FOOD ITEMS BY CALORIES
# ==============================

top = df.nlargest(20, "Calories")

plt.figure(figsize=(12, 6))

plt.bar(
    top["Item"],
    top["Calories"]
)

plt.xticks(rotation=60, ha="right")

plt.xlabel("Food Item")
plt.ylabel("Calories (kcal)")
plt.title("Top 20 Food Items by Calories")

plt.tight_layout()
plt.show()